package pc2.lab.aula09.model.enums;

public enum EnumMenuOption {
   MAKERENDER,RIGHT,TEXT, RECTANGLE, SQUARE, LOZENGE, TRAPEZE, TRIANGLE, TRIANGLERIGHT, TRIANGLEISOSCELES, TRIANGLEEQUILATERAL, CIRCLE, LIST, DELETE, DRAW, SAVE, RECOVER, END,
   CREATE,EDIT, SHOW, BACK
}