package pc2.lab.aula09.model.enums;

public enum EnumMenuOption {
   MAKEFIGURA, RECTANGLE, SQUARE, LOZENGE, TRAPEZE, TRIANGLERIGHT, TRIANGLEISOSCELES, TRIANGLEEQUILATERAL, CIRCLE, LIST, DELETE, DRAW, END,
   NEWRECTANGLE, NEWSQUARE, NEWLOZENGE, NEWTRIANGLE, NEWCIRCLE, NEWPOINT, NEWRIGHT,EDIT, SHOW
}