package pc2.lab.aula09.model.enums;

public enum EnumMenuOption {
    QUADRILATER, RECTANGLE, SQUARE, LOZENGE, TRAPEZE, TRIANGLERIGHT, TRIANGLEISOSCELES, TRIANGLEEQUILATERAL, CIRCLE, LIST, DELETE, DRAW, END
}